# Generated by Django 4.2.11 on 2026-03-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used as the login identifier', max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Display name shown to other users and in recommendations', max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (stored in media/avatars/)', null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django admin panel')),
                ('is_onboarded', models.BooleanField(default=False, help_text='Has the user completed the initial genre preference setup?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_services', models.JSONField(blank=True, default=list, help_text="User's active streaming subscriptions for filtering watch links")),
                ('preferred_language', models.CharField(default='en', help_text='ISO language code: en, hi, fr, etc.', max_length=10)),
                ('include_adult_content', models.BooleanField(default=False, help_text='Show R-rated / adult content in recommendations')),
                ('total_movies_watched', models.PositiveIntegerField(default=0)),
                ('total_hours_watched', models.FloatField(default=0.0)),
                ('avg_rating_given', models.FloatField(blank=True, help_text='Rolling average of all ratings given by this user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_genres', models.ManyToManyField(blank=True, help_text='Genres selected during onboarding or updated in settings', related_name='interested_users', to='movies.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'users_userprofile',
            },
        ),
    ]
