# Generated by Django 4.2.11 on 2026-03-17 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Rating from 1.0 to 10.0 (supports half-stars)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('review', models.TextField(blank=True, help_text='Optional written review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interactions_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=1, help_text='Incremented on repeat views instead of creating new records')),
            ],
            options={
                'db_table': 'interactions_viewhistory',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='Where they watched it: Netflix, Prime, Theatre, etc.', max_length=50)),
                ('rewatched', models.BooleanField(default=False, help_text='True if user has watched this before (additional signal)')),
            ],
            options={
                'db_table': 'interactions_watchevent',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, help_text='Optional personal note about why saved', max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='movies.movie')),
            ],
            options={
                'db_table': 'interactions_watchlistitem',
                'ordering': ['-added_at'],
            },
        ),
    ]
