# Generated by Django 4.2.11 on 2026-03-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'movie'], name='interaction_user_id_28a3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'score'], name='interaction_movie_i_97e0b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
    ]
