# Generated by Django 4.2.11 on 2026-03-17 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, help_text='TMDB genre ID - used to sync with TMDB API', null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for UI display: 🎬 💥 😂 etc.', max_length=10)),
            ],
            options={
                'db_table': 'movies_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, help_text='TMDB movie ID — primary link to external data', unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('overview', models.TextField(blank=True, help_text='Movie synopsis / description (from TMDB)')),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('original_language', models.CharField(default='en', max_length=10)),
                ('adult', models.BooleanField(default=False, help_text='Adult content flag — hidden by default (see UserProfile.include_adult_content)')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, db_index=True, help_text='Denormalized year for faster filtering', null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('vote_average', models.FloatField(default=0.0, help_text='TMDB community rating (0-10) — used in cold-start recommendations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.FloatField(default=0.0, help_text='TMDB popularity score — trending metric')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Topic keywords for content-based ML features')),
                ('content_vector', models.JSONField(blank=True, help_text='Pre-computed content feature vector (DO NOT EDIT MANUALLY)', null=True)),
                ('poster_path', models.CharField(blank=True, help_text='TMDB poster path (append to TMDB_IMAGE_BASE to get full URL)', max_length=300)),
                ('backdrop_path', models.CharField(blank=True, help_text='TMDB backdrop path — used as hero image in movie detail page', max_length=300)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('In Production', 'In Production'), ('Post Production', 'Post Production'), ('Planned', 'Planned'), ('Canceled', 'Canceled')], default='Released', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When TMDB data was last refreshed for this movie', null=True)),
            ],
            options={
                'db_table': 'movies_movie',
                'ordering': ['-popularity', '-vote_average'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('profile_image_url', models.URLField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies_person',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StreamingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime Video'), ('disney', 'Disney+'), ('hotstar', 'Hotstar'), ('hulu', 'Hulu'), ('hbo', 'HBO Max'), ('apple', 'Apple TV+'), ('mubi', 'MUBI'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=50)),
                ('provider_name', models.CharField(max_length=100)),
                ('link_type', models.CharField(choices=[('stream', 'Stream'), ('rent', 'Rent'), ('buy', 'Buy'), ('free', 'Free with Ads')], default='stream', max_length=20)),
                ('url', models.URLField(help_text='Direct link to movie on the streaming platform')),
                ('region', models.CharField(default='IN', help_text='ISO country code: IN, US, UK, etc.', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in local currency (for rent/buy types)', max_digits=8, null=True)),
                ('provider_logo', models.URLField(blank=True, help_text='URL to provider logo image')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_links', to='movies.movie')),
            ],
            options={
                'db_table': 'movies_streaminglink',
                'ordering': ['provider', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(help_text='e.g., Director, Screenplay, Cinematography', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'movies_moviecrew',
                'unique_together': {('movie', 'person', 'job')},
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Billing order (0 = top billed)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'movies_moviecast',
                'ordering': ['order'],
                'unique_together': {('movie', 'person', 'character')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_in', through='movies.MovieCast', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='worked_on', through='movies.MovieCrew', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Primary content feature for content-based filtering', related_name='movies', to='movies.genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year', 'vote_average'], name='movies_movi_release_468486_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'),
        ),
    ]
