"""
============================================================
CineMatch - API URL Router (api/urls.py)
============================================================

The DRF Router automatically generates URL patterns from ViewSets.

HOW DRF ROUTER WORKS:
  router.register(prefix, ViewSet, basename)

  For a ModelViewSet or ReadOnlyModelViewSet, the router generates:
    GET    /prefix/          → list()
    POST   /prefix/          → create()
    GET    /prefix/{pk}/     → retrieve()
    PUT    /prefix/{pk}/     → update()
    PATCH  /prefix/{pk}/     → partial_update()
    DELETE /prefix/{pk}/     → destroy()

  For custom @action decorators:
    detail=False → /prefix/action_name/
    detail=True  → /prefix/{pk}/action_name/

FULL API URL MAP:
  Auth:
    POST /api/v1/auth/register/         → AuthViewSet.register()
    POST /api/v1/auth/login/            → AuthViewSet.login()
    POST /api/v1/auth/logout/           → AuthViewSet.logout()
    GET  /api/v1/auth/me/               → AuthViewSet.me()
    PUT  /api/v1/auth/profile/          → AuthViewSet.profile()
    POST /api/v1/auth/onboarding/       → AuthViewSet.onboarding()
    POST /api/v1/auth/token/refresh/    → TokenRefreshView (SimpleJWT)

  Movies:
    GET  /api/v1/movies/                → MovieViewSet.list()
    GET  /api/v1/movies/{id}/           → MovieViewSet.retrieve()
    GET  /api/v1/movies/trending/       → MovieViewSet.trending()
    GET  /api/v1/movies/top-rated/      → MovieViewSet.top_rated()
    GET  /api/v1/movies/genre/{slug}/   → MovieViewSet.by_genre()
    GET  /api/v1/movies/{id}/similar/   → MovieViewSet.similar()
    POST /api/v1/movies/{id}/rate/      → MovieViewSet.rate()
    POST /api/v1/movies/{id}/viewed/    → MovieViewSet.record_view()

  Genres:
    GET  /api/v1/genres/                → GenreViewSet.list()

  Watchlist:
    GET    /api/v1/watchlist/                   → WatchlistViewSet.list()
    POST   /api/v1/watchlist/                   → WatchlistViewSet.create()
    DELETE /api/v1/watchlist/{id}/              → WatchlistViewSet.destroy()
    DELETE /api/v1/watchlist/movie/{movie_id}/  → WatchlistViewSet.remove_by_movie()

  Watch History:
    GET  /api/v1/watched/               → WatchedViewSet.list()
    POST /api/v1/watched/               → WatchedViewSet.create()

  Ratings:
    GET  /api/v1/ratings/               → RatingViewSet.list()

  Recommendations:
    GET  /api/v1/recommendations/              → RecommendationViewSet.list()
    POST /api/v1/recommendations/refresh/      → RecommendationViewSet.refresh()
    POST /api/v1/recommendations/{id}/clicked/ → RecommendationViewSet.mark_clicked()

  Dashboard:
    GET  /api/v1/dashboard/             → DashboardView.get()

All prefixed with /api/v1/ (set in core/urls.py).
============================================================
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import (
    AuthViewSet,
    MovieViewSet,
    GenreViewSet,
    WatchlistViewSet,
    WatchedViewSet,
    RatingViewSet,
    RecommendationViewSet,
    DashboardView,
)

# ============================================================
# DRF DEFAULT ROUTER
# ============================================================
# DefaultRouter also generates a browsable API root at /api/v1/
# that lists all registered endpoints. Very useful during development.
router = DefaultRouter()

# --- Auth ---
router.register(r'auth', AuthViewSet, basename='auth')

# --- Movies ---
router.register(r'movies', MovieViewSet, basename='movie')

# --- Genres ---
router.register(r'genres', GenreViewSet, basename='genre')

# --- Interactions ---
router.register(r'watchlist', WatchlistViewSet, basename='watchlist')
router.register(r'watched', WatchedViewSet, basename='watched')
router.register(r'ratings', RatingViewSet, basename='rating')

# --- Recommendations ---
router.register(r'recommendations', RecommendationViewSet, basename='recommendation')


# ============================================================
# URL PATTERNS
# ============================================================
urlpatterns = [
    # All ViewSet routes auto-generated by router
    path('', include(router.urls)),

    # JWT Token Refresh (SimpleJWT provides this view directly)
    # POST /api/v1/auth/token/refresh/  →  { "refresh": "<token>" }
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Dashboard — single GenericAPIView (not a ViewSet)
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]