# Generated by Django 4.2.11 on 2026-03-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation confidence score (0-1, higher = more confident)')),
                ('rank', models.PositiveIntegerField(default=0, help_text="Position in user's recommendation list (1 = top pick)")),
                ('reason_code', models.CharField(choices=[('watched_similar', 'Because you watched similar movies'), ('genre_match', 'Matches your preferred genres'), ('director_fan', 'You like this director'), ('actor_fan', 'Features your favorite actors'), ('users_like_you', 'Users like you enjoyed this'), ('trending', 'Trending now'), ('highly_rated', 'Critically acclaimed'), ('hidden_gem', 'Hidden gem you might have missed')], default='watched_similar', help_text='Primary reason this was recommended (for UI display)', max_length=30)),
                ('reason_text', models.CharField(blank=True, help_text="Human-readable explanation: 'Because you rated Inception 9/10'", max_length=200)),
                ('was_clicked', models.BooleanField(default=False, help_text='User clicked on this recommendation')),
                ('was_rated', models.BooleanField(default=False, help_text='User later rated this movie')),
                ('was_added_to_watchlist', models.BooleanField(default=False, help_text='User added this to watchlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendations_recommendation',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_used', models.CharField(choices=[('hybrid', 'Hybrid (CF + Content-Based)'), ('content', 'Content-Based Only'), ('collaborative', 'Collaborative Filtering Only'), ('popularity', 'Popularity-Based'), ('genre', 'Genre-Based')], default='hybrid', help_text='Which ML algorithm generated this batch', max_length=20)),
                ('num_recommendations', models.PositiveIntegerField(default=0)),
                ('cf_weight_used', models.FloatField(blank=True, help_text='Actual collaborative filtering weight used (0-1)', null=True)),
                ('content_weight_used', models.FloatField(blank=True, help_text='Actual content-based weight used (0-1)', null=True)),
                ('ratings_available', models.IntegerField(default=0, help_text='How many ratings the user had at generation time')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this datetime, recs should be regenerated', null=True)),
            ],
            options={
                'db_table': 'recommendations_batch',
                'ordering': ['-generated_at'],
                'get_latest_by': 'generated_at',
            },
        ),
        migrations.CreateModel(
            name='SimilarMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score (0-1)')),
                ('shared_genres', models.JSONField(blank=True, default=list, help_text='Genre names shared between the two movies')),
                ('shared_cast', models.JSONField(blank=True, default=list, help_text='Actor names shared between the two movies')),
                ('same_director', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='movies.movie')),
                ('similar_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='movies.movie')),
            ],
            options={
                'db_table': 'recommendations_similarmovie',
                'ordering': ['-similarity_score'],
            },
        ),
    ]
