# Generated by Django 4.2.11 on 2026-03-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationbatch'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source_movie',
            field=models.ForeignKey(blank=True, help_text='The movie that triggered this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_recommendations', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='similarmovie',
            unique_together={('movie', 'similar_movie')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'rank'], name='recommendat_user_id_d215ce_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'score'], name='recommendat_user_id_88af3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'movie', 'batch')},
        ),
    ]
